name: skyangel_mobile
description: "SkyAngel Mobile - Security and risk analysis platform for transportation in Mexico"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter

  # State Management & Architecture
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  hooks_riverpod: ^2.4.9
  flutter_hooks: ^0.20.5
  get_it: ^7.6.4
  injectable: ^2.3.2

  # Networking & APIs
  dio: ^5.4.0
  retrofit: ^4.1.0
  json_annotation: ^4.8.1
  socket_io_client: ^2.0.3+1
  # dio_certificate_pinning: ^3.0.5  # Package not available

  # Maps & Location
  flutter_map: ^6.1.0
  latlong2: ^0.9.1
  geolocator: ^10.1.0
  # background_location: ^0.12.0  # Package not available
  # flutter_compass: ^0.8.0  # Package not available
  # geodesy: ^0.4.0  # Package not available
  maps_launcher: ^2.2.1

  # Data Visualization
  fl_chart: ^0.66.0
  # syncfusion_flutter_charts: ^21.2.10  # Large package, optional
  # graphic: ^2.2.0  # Package incompatible

  # Storage & Persistence
  drift: ^2.14.1
  sqlite3_flutter_libs: ^0.5.18
  path_provider: ^2.1.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.2
  cached_network_image: ^3.3.1

  # UI/UX Components
  # material_color_utilities: ^0.5.0  # Conflicts with Flutter SDK
  dynamic_color: ^1.6.8
  rive: ^0.12.4
  lottie: ^2.7.0
  shimmer: ^3.0.0
  flutter_staggered_animations: ^1.1.1
  photo_view: ^0.14.0
  carousel_slider: ^4.2.1

  # Navigation & Routing
  go_router: ^12.1.3

  # Authentication & Security
  local_auth: ^2.1.7
  crypto: ^3.0.3
  encrypt: ^5.0.3
  device_info_plus: ^9.1.1
  package_info_plus: ^4.2.0
  amazon_cognito_identity_dart_2: ^3.6.3
  # trust_fall: ^3.0.1  # Removed due to version incompatibility

  # Utilities
  # intl: ^0.19.0  # Managed by Flutter SDK
  uuid: ^4.3.3
  url_launcher: ^6.2.3
  share_plus: ^7.2.1
  permission_handler: ^11.1.0
  connectivity_plus: ^5.0.2
  app_settings: ^5.1.1
  freezed_annotation: ^2.4.1
  logger: ^2.0.2+1
  pretty_dio_logger: ^1.3.1
  dartz: ^0.10.1

  # Firebase & Analytics
  firebase_core: ^2.24.2
  firebase_analytics: ^10.7.4
  firebase_crashlytics: ^3.4.8
  firebase_performance: ^0.9.3+8
  firebase_messaging: ^14.7.10
  firebase_remote_config: ^4.3.8

  # Image Processing
  image_picker: ^1.0.6
  # image_cropper: ^5.0.1  # Temporarily disabled due to compilation issues
  flutter_image_compress: ^2.1.0

  # Internationalization
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  
  # Code Generation
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  riverpod_generator: ^2.3.9
  retrofit_generator: ^8.1.0
  injectable_generator: ^2.4.1
  drift_dev: ^2.14.1
  hive_generator: ^2.0.1
  freezed: ^2.4.6
  auto_route_generator: ^7.3.2

  # Testing
  mocktail: ^1.0.3
  patrol: ^3.6.1
  golden_toolkit: ^0.15.0
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/lottie/
    - assets/rive/
    - assets/geojson/
    - assets/config/

  # fonts:
  #   - family: Roboto
  #     fonts:
  #       - asset: assets/fonts/Roboto-Regular.ttf
  #       - asset: assets/fonts/Roboto-Bold.ttf
  #         weight: 700
  #   - family: Inter
  #     fonts:
  #       - asset: assets/fonts/Inter-Regular.ttf
  #       - asset: assets/fonts/Inter-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/Inter-Bold.ttf
  #         weight: 700

flutter_intl:
  enabled: true
  main_locale: es
  arb_dir: lib/l10n
  output_dir: lib/generated
  use_deferred_loading: false