// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'demo-api-key',
    appId: '1:demo-project:web:demo-app-id',
    messagingSenderId: 'demo-sender-id',
    projectId: 'skyangel-mobile-demo',
    authDomain: 'skyangel-mobile-demo.firebaseapp.com',
    storageBucket: 'skyangel-mobile-demo.appspot.com',
    measurementId: 'G-DEMO',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'demo-api-key',
    appId: '1:demo-project:android:demo-app-id',
    messagingSenderId: 'demo-sender-id',
    projectId: 'skyangel-mobile-demo',
    storageBucket: 'skyangel-mobile-demo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'demo-api-key',
    appId: '1:demo-project:ios:demo-app-id',
    messagingSenderId: 'demo-sender-id',
    projectId: 'skyangel-mobile-demo',
    authDomain: 'skyangel-mobile-demo.firebaseapp.com',
    storageBucket: 'skyangel-mobile-demo.appspot.com',
    iosBundleId: 'com.skyangel.mobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'demo-api-key',
    appId: '1:demo-project:macos:demo-app-id',
    messagingSenderId: 'demo-sender-id',
    projectId: 'skyangel-mobile-demo',
    authDomain: 'skyangel-mobile-demo.firebaseapp.com',
    storageBucket: 'skyangel-mobile-demo.appspot.com',
    iosBundleId: 'com.skyangel.mobile',
  );
}