# Usa una imagen base de Python
FROM python:3.11-slim

# Establece el directorio de trabajo en el contenedor
WORKDIR /app

# Copia el archivo de requerimientos y lo instala
COPY req_ubuntu.txt .

RUN apt update
RUN pip install --upgrade pip
RUN apt install -y locales libpq-dev build-essential gcc
RUN pip install -r req_ubuntu.txt
RUN pip install eventlet gunicorn && \
    sed -i '/es_MX.UTF-8/s/^# //g' /etc/locale.gen && \
    locale-gen es_MX.UTF-8 && \
    update-locale

# Copia todo el código de tu aplicación al directorio de trabajo
COPY . .

# Expone el puerto en el que corre la aplicación (ajústalo según tu configuración Flask)
EXPOSE 5000

# Define el comando por defecto para correr la aplicación
#CMD ["python3", "run.py"]
CMD ["gunicorn", "-k", "eventlet", "-w", "1", "run:app", "--bind", "0.0.0.0:5000", "--access-logfile", "-", "--error-logfile", "-"]