/**** SECRETARIADO ****/

TableGroup "SECRETARIADO" [color: #011B4E]{
  CAT_BIEN_JURIDICO_AFECTADO
  CAT_TIPO_DE_DELITO
  CAT_SUBTIPO_DE_DELITO
  CAT_MODALIDAD
  CAT_DELITOS_SECRETARIADO
  SUM_DELITOS_MUNICIPIO_MES
}

TABLE CAT_BIEN_JURIDICO_AFECTADO [headercolor: #011B4E] {
  ID_BIEN_JURIDICO_AFECTADO int [pk]
  BIEN_JURIDICO_AFECTADO varchar(100)   
}

TABLE CAT_TIPO_DE_DELITO [headercolor: #011B4E] {
  ID_TIPO_DE_DELITO int [pk]
  ID_BIEN_JURIDICO_AFECTADO int
  TIPO_DE_DELITO varchar(100)
}

TABLE CAT_SUBTIPO_DE_DELITO [headercolor: #011B4E] {
  ID_SUBTIPO_DE_DELITO int [pk]
  ID_TIPO_DE_DELITO int
  SUBTIPO_DE_DELITO varchar(100)
}

TABLE CAT_MODALIDAD [headercolor: #011B4E] {
  ID_MODALIDAD int [pk]
  MODALIDAD varchar(500)
}

TABLE CAT_DELITOS_SECRETARIADO [headercolor: #011B4E] {
  ID_DELITO int [pk] //este me ayuda a distinguir si es del secretariado o sky
  ID_MODALIDAD int
  ID_SUBTIPO_DE_DELITO int
}

TABLE SUM_DELITOS_MUNICIPIO_MES [headercolor: #011B4E] {
  ID_DELITO int
  ID_MUNICIPIO int
  ID_MES int
  ANIO int
  CONTEO int
}

/**** FUENTES EXTERNAS ****/

TableGroup "FUENTES EXTERNAS" [color: #1E69FD]{
  SUM_DELITOS_NACIONAL_MES_ANERPV
  SUM_DELITOS_MUNICIPIO_MES_ANERPV
  SUM_DELITOS_ENTIDAD_MES_ANERPV
  SUM_DELITOS_ENTIDAD_MES_MODALIDAD_ANERPV
  CAT_MODALIDAD_ANERPV
}

TABLE SUM_DELITOS_NACIONAL_MES_ANERPV [headercolor: #1E69FD] {
  ANIO int
  ID_MES int
  CONTEO_ROBO_TRANSPORTISTA int
  CONTEO_ROBO_TRANSPORTISTA_ACUMULADO int
  CONTEO_ROBO_VEHICULOS_PESADOS int
  CONTEO_ROBO_VEHICULOS_LIGEROS int
  CONTEO_ROBO_VEHICULOS_PRIVADOS int
  CONTEO_ROBO_TURNO_MATUTINO int
  CONTEO_ROBO_TURNO_MADRUGADA int
  CONTEO_ROBO_TURNO_VESPERTINO int
  CONTEO_ROBO_TURNO_NOCTURNO int
  CONTEO_ROBO_LUNES int
  CONTEO_ROBO_MARTES int
  CONTEO_ROBO_MIERCOLES int
  CONTEO_ROBO_JUEVES int
  CONTEO_ROBO_VIERNES int
  CONTEO_ROBO_SABADO int
  CONTEO_ROBO_DOMINGO int
}

TABLE SUM_DELITOS_MUNICIPIO_MES_ANERPV [headercolor: #1E69FD] {
  CVE_MUNICIPIO int
  ANIO int
  ID_MES int
  CONTEO_ROBO_TRANSPORTISTA int
  CONTEO_ROBO_TRANSPORTISTA_ACUMULADO int
}

TABLE SUM_DELITOS_ENTIDAD_MES_ANERPV [headercolor: #1E69FD] {
  ID_ENTIDAD int
  ANIO int
  ID_MES int
  CONTEO_ROBO_TRANSPORTISTA int
  CONTEO_ROBO_TRANSPORTISTA_ACUMULADO int
  CONTEO_ROBO_VEHICULOS_PESADOS int
  CONTEO_ROBO_VEHICULOS_LIGEROS int
  CONTEO_ROBO_VEHICULOS_PRIVADOS int
  CONTEO_ROBO_TURNO_MATUTINO int
  CONTEO_ROBO_TURNO_MADRUGADA int
  CONTEO_ROBO_TURNO_VESPERTINO int
  CONTEO_ROBO_TURNO_NOCTURNO int
}

TABLE SUM_DELITOS_ENTIDAD_MES_MODALIDAD_ANERPV [headercolor: #1E69FD] {
  ID_ENTIDAD int
  ANIO int
  ID_MES int
  ID_MODALIDAD_ANERPV int
  CONTEO_ROBO_TRANSPORTISTA int
  CONTEO_ROBO_TRANSPORTISTA_ACUMULADO int
}

TABLE CAT_MODALIDAD_ANERPV [headercolor: #1E69FD] {
  ID_MODALIDAD_ANERPV int
  MODALIDAD_ANERPV varchar(50)
}

/**** REACCIONES ****/

TableGroup "REACCIONES" [color: #990D0D]{
  INCIDENTES_SKY
  CAT_CENTRAL
  CAT_LINEA_TRANSPORTISTA
  CAT_OPERADORES
  CAT_CATEGORIAS
}

TABLE INCIDENTES_SKY [headercolor: #990D0D] {
  ID_INCIDENTE int [pk]
  ID_MES int
  DIA int
  ANIO int
  DIA_SEMANA varchar(9)
  CVE_MUNICIPIO int
  DESCRIPCION_INCIDENTE text
  ID_CATEGORIA int
  PLACAS varchar(200)
  ID_CENTRAL int
  ID_LINEA_TRANSPORTISTA int
  ID_OPERADOR int
  FECHA_INCIDENTE date
  HR_DE_INICIO time
  HR_DE_TERMINO time
  LATITUD_INCIDENTE decimal (9,6)
  LONGITUD_INCIDENTE decimal (9,6)
  LATITUD_LOCALIZACION decimal (9,6)
  LONGITUD_LOCALIZACION decimal (9,6)
  OBSERVACION text
}

Ref: "INCIDENTES_SKY".ID_MES > "CAT_MESES".ID_MES [color: #990D0D]

TABLE CAT_CENTRAL [headercolor: #990D0D] {
  ID_CENTRAL int [pk]
  CENTRAL varchar(50)
}

TABLE CAT_LINEA_TRANSPORTISTA [headercolor: #990D0D] {
  ID_LINEA_TRANSPORTISTA int [pk]
  LINEA_TRANSPORTISTA varchar(200)
}

TABLE CAT_OPERADORES [headercolor: #990D0D] {
  ID_OPERADOR int
  OPERADOR_DE_UNIDAD varchar(200)
}

TABLE CAT_CATEGORIAS [headercolor: #990D0D] {
  ID_CATEGORIA int [pk]
  CATEGORIAS varchar(100)   
}

/*** ROBO Y VANDALISMO SISTEMA FERROVIARIO MEXICO ***/

TableGroup "ROBO Y VANDALISMO SISTEMA FERROVIARIO MEXICO" [color: #E4A62E]{
  FER_DELITOS
  FER_SUBDELITOS
  FER_DELITOS_SUBDELITOS
  FER_REGISTROS
}

TABLE FER_DELITOS [headercolor: #E4A62E] {
  ID_FER_DELITO int [pk]
  FER_DELITO varchar(20)
}

TABLE FER_SUBDELITOS [headercolor: #E4A62E] {
  ID_FER_SUBDELITO int [pk]
  FER_SUBDELITO varchar(40)
}

TABLE FER_DELITOS_SUBDELITOS [headercolor: #E4A62E] {
  ID_FER_DELITO_SUBDELITO int [pk]
  ID_FER_DELITO int
  ID_FER_SUBDELITO int
}

TABLE FER_REGISTROS [headercolor: #E4A62E] {
  ID_FER_REGISTRO int [pk]
  DIA smallint
  MES smallint
  ANIO smallint
  ID_ENTIDAD int
  CVE_MUNICIPIO int
  ID_FER_DELITO int
  ID_FER_SUBDELITO int
}

/**** PUNTO DE INTERES ****/

TableGroup "PUNTO DE INTERES" [color: #A15CF5]{
  INT_INC_DELICTIVAS
  INT_OTRAS_INCIDENCIAS
  INT_ACCIDENTES
  INT_RECUPERACION
  INT_CACHIMBAS
  INT_COBERTURA
  INT_CORRALONES
  INT_GUARDIA_NACIONAL
  INT_MINISTERIOS_PUBLICOS
  INT_PARADEROS
}

TABLE INT_INC_DELICTIVAS [headercolor: #A15CF5] {
  ID_INT_INC_DELICTIVAS int [pk]
  DIA varchar(9)
  MES int
  ANIO int
  OPERADOR_DE_UNIDAD varchar(100)
  CATEGORIA varchar(50)
  CENTRAL varchar(30)
  LINEA_TRANSPORTISTA varchar(60)
  LATITUD decimal(9,6)
  LONGITUD decimal(9,6)
  ID_ENTIDAD int
  CVE_MUNICIPIO int
}

TABLE INT_OTRAS_INCIDENCIAS [headercolor: #A15CF5] {
  ID_INT_OTRAS_INCIDENCIAS int [pk]
  DIA varchar(9)
  MES int
  ANIO int
  CATEGORIA varchar(50)
  CENTRAL varchar(30)
  LATITUD decimal(9,6)
  LONGITUD decimal(9,6)
  ID_ENTIDAD int
  CVE_MUNICIPIO int
}

TABLE INT_ACCIDENTES [headercolor: #A15CF5] {
  ID_INT_ACCIDENTES int [pk]
  DIA varchar(9)
  MES int
  ANIO int
  CATEGORIA varchar(50)
  CENTRAL varchar(30)
  LATITUD decimal(9,6)
  LONGITUD decimal(9,6)
  ID_ENTIDAD int
  CVE_MUNICIPIO int
}

TABLE INT_RECUPERACION [headercolor: #A15CF5] {
  ID_INT_RECUPERACION int [pk]
  DIA varchar(9)
  MES int
  ANIO int
  OPERADOR_DE_UNIDAD varchar(100)
  CATEGORIA varchar(50)
  CENTRAL varchar(30)
  LINEA_TRANSPORTISTA varchar(60)
  LATITUD decimal(9,6)
  LONGITUD decimal(9,6)
  ID_ENTIDAD int
  CVE_MUNICIPIO int
}

TABLE INT_CACHIMBAS [headercolor: #A15CF5] {
  ID_INT_CACHIMBA int [pk]
  INT_CACHIMBA varchar(100)
  LATITUD decimal(9,6)
  LONGITUD decimal(9,6)
  ID_ENTIDAD int
  CVE_MUNICIPIO int
}

TABLE INT_COBERTURA [headercolor: #A15CF5] {
  ID_INT_COBERTURA int [pk]
  COBERTURA_GPS_FIJO decimal(21,18)
  COBERTURA_GPS_MOVIL decimal(21,18)
  FLUJO_TERRESTRE int
  LATITUD decimal(9,6)
  LONGITUD decimal(9,6)
  ID_ENTIDAD int
  CVE_MUNICIPIO int
}

TABLE INT_CORRALONES [headercolor: #A15CF5] {
  ID_INT_CORRALON int [pk]
  CORRALON varchar(100)
  DIRECCION varchar(180)
  ENLACE text
  TELEFONO text
  CORREO_ELECTRONICO text
  LATITUD decimal(9,6)
  LONGITUD decimal(9,6)
  ID_ENTIDAD int
  CVE_MUNICIPIO int
}

TABLE INT_GUARDIA_NACIONAL [headercolor: #A15CF5] {
  ID_INT_GUARDIA_NACIONAL int [pk]
  CORRALON varchar(100)
  ENLACE text
  ZONA varchar(10)
  INSTALACION varchar(50)
  ESTACION varchar(100)
  DIRECCION varchar(180)
  LATITUD decimal(9,6)
  LONGITUD decimal(9,6)
  ID_ENTIDAD int
  CVE_MUNICIPIO int
}

TABLE INT_MINISTERIOS_PUBLICOS [headercolor: #A15CF5] {
  ID_INT_MINISTERIO_PUBLICO int [pk]
  INT_MINISTERIO_PUBLICO varchar(120)
  DIRECCION varchar(180)
  DELEGACION varchar(30)
  ENLACE text
  TELEFONO varchar(50)
  CORREO_ELECTRONICO text
  LATITUD decimal(9,6)
  LONGITUD decimal(9,6)
  MUNICIPIO varchar(50)
  ID_ENTIDAD int
  CVE_MUNICIPIO int
}

TABLE INT_PARADEROS [headercolor: #A15CF5] {
  ID_INT_PARADEROS int [pk]
  C varchar(5)
  ENLACE text
  NAME varchar(100)
  _DESCRIPTION varchar(100)
  _CUSTOM_ID varchar(36)
  ID varchar(5)
  LLAVE_CIERRE varchar(5)
  ENLACE1 text
  KM varchar(10)
  CARRETERA varchar(100)
  PARADORES_RECOMENDADOS varchar(150)
  ORIGEN varchar(100)
  DESTINO varchar(100)
  TRAMO varchar(100)
  POBLACION_Y_O_MUNICIPIO varchar(100)
  CORREDOR_SEGURO varchar(100)
  ESTACION_DE_SERVICIOS int
  GASOLINERA int
  BANOS int
  ALIMENTOS int
  TELEFONO_PUBLICO int
  SERVICIO_MEDICO int
  MECANICO int
  MECANICO_Y_O_VULCANIZADORA int
  SRV_GRUA int
  TAXI int
  SERVICIO_PUBLICO_Y_AMBULACINCIA int
  TIENDA_AUTO_SERVICIO int
  HOTEL int
  ESTACIONAMIENTO int
  ESTACIONAMIENTO1 int
  ESTACIONAMINTO int
  RETORNO int
  ZONNA_DE_RIEZGOO_BAJO int
  ZONA_DE_RIESGO_MEDIO int
  ZONA_DE_DESCANSO int
  ALIMENTOS1 int
  ZONA_DE_ESTACIONAMIENTO int
  TIENDA int
  ESTACION_GN int
  PENSION int
  ZONA_DE_SERVICIOS int
  SANITARIOS int
  VIJILANCIA_ILUMINADA int
  GASOLINERA1 int
  LATITUD decimal(9,6)
  LONGITUD decimal(9,6)
  ID_ENTIDAD int
  CVE_MUNICIPIO int
}

/**** ALERTAS SKY ****/

TableGroup "ALERTAS SKY" [color: #79AD51] {
  ALERTAS_SKY
  CAT_ESTATUS_ALERTA
}

TABLE ALERTAS_SKY {
  ID_ALERTA INT [pk]
  TIPO_ALERTA VARCHAR(30)
  INCIDENCIA_ALERTA VARCHAR(50)
  FECHA_ALERTA DATE
  DIA_SEMANA VARCHAR(9)
  HORA_ALERTA TIME
  COMENTARIO_ALERTA TEXT
  OPERADOR_DE_UNIDAD VARCHAR(200) [NULL] 
  CENTRAL VARCHAR(50) [NULL]
  LINEA_TRANSPORTISTA VARCHAR(200) [NULL]
  LATITUD_ALERTA DECIMAL(9,6)
  LONGITUD_ALERTA DECIMAL(9,6)
  ID_ESTATUS_ALERTA INT
}

TABLE CAT_ESTATUS_ALERTA {
  ID_ESTATUS_ALERTA INT [pk]
  ESTATUS_ALERTA VARCHAR(9)
}

/**** CATALOGOS ****/

TableGroup "CATALOGOS" {
  CAT_MESES
  CAT_TRIMESTRES
  CATALOGO_MUNICIPIO
  CAT_ENTIDAD
}

TABLE CAT_MESES {
  ID_MES int [pk]
  ID_TRIMESTRE int
  MES varchar(20)   
}

TABLE CAT_TRIMESTRES {
  ID_TRIMESTRE int [pk]
  TRIMESTRE varchar(20)   
}

TABLE CATALOGO_MUNICIPIO {
  CVE_MUNICIPIO int [pk]
  MUNICIPIO varchar(50)
  LATITUD_CENTROIDE DECIMAL(9,6)
  LONGITUD_CENTROIDE DECIMAL(9,6)
  ID_ENTIDAD int
}

TABLE CAT_ENTIDAD{ 
  ID_ENTIDAD int [pk]
  ENTIDAD varchar(50)
  ABREVIATURA varchar(5)
}

/**** SE VAN A ELIMINAR LAS TABLAS ****/

/*

// REACCIONES
TABLE DELITOS_INCIDENTES_SKY [headercolor: #990D0D] {
  ID_INCIDENTE int [ref: > INCIDENTES_SKY.ID_INCIDENTE]
  ID_SUBTIPO_DE_DELITO int [ref: > CAT_SUBTIPO_DE_DELITO.ID_SUBTIPO_DE_DELITO]
}

TABLE INCIDENTES_RECUPERADOS [headercolor: #990D0D] {
  ID_INCIDENTE int [ref: > INCIDENTES_SKY.ID_INCIDENTE]
  CVE_MUNICIPIO int [ref: > CATALOGO_MUNICIPIO.CVE_MUNICIPIO]
  FECHA_RECUPERACION date // PEDIRLA A SKY
  LATITUD_LOCALIZACION decimal (9,6)
  LONGITUD_LOCALIZACION decimal (9,6)
}

// SECRETARIADO
TABLE DELITOS_SECRETARIADO_MUNICIPIO [headercolor: #011B4E] {
  ID_TIPO_DE_DELITO int [ref: > CAT_DELITOS_SECRETARIADO.ID_DELITO]
  ID_DELITO_MUNICIPIO int [pk]
  CVE_MUNICIPIO int [ref: > CATALOGO_MUNICIPIO.CVE_MUNICIPIO] 
}

TABLE SUM_DELITOS_MUNICIPIO_MES_SECRETARIADO [headercolor: #1E69FD] {
  CVE_MUNICIPIO int [ref: > CATALOGO_MUNICIPIO.CVE_MUNICIPIO]
  ID_TIPO_DE_DELITO int [ref: > CAT_DELITOS_SECRETARIADO.ID_DELITO]
  ID_MES int [ref: > CAT_MESES.ID_MES]
  //ID_DELITO_MUNICIPIO int [ref: > DELITOS_SECRETARIADO_MUNICIPIO.ID_DELITO_MUNICIPIO]
  ANIO int
  CONTEO_SECRETARIADO int
}

TABLE FUENTE_DELITO [headercolor: #1E69FD]{
  ID_INDICE_MAYOR_ROBO int
  CVE_MUNICIPIO int
  MUNICIPIO varchar(50)
  ID_TIPO_VEHICULO int
  ANIO int
  ID_MES int
  CONTEO_MES int
  CONTEO_ACUM int [NOTE: "SUMA CONTEO MES A MES"]

*/

/**** CATALOGOS ****/
Ref: "CAT_MESES".ID_TRIMESTRE > "CAT_TRIMESTRES".ID_TRIMESTRE [color: #000]
Ref: "CATALOGO_MUNICIPIO".ID_ENTIDAD > "CAT_ENTIDAD".ID_ENTIDAD [color: #000]

/**** SECRETARIADO ****/
Ref: "SUM_DELITOS_MUNICIPIO_MES".ID_MUNICIPIO > "CATALOGO_MUNICIPIO".CVE_MUNICIPIO [color: #011B4E]
Ref: "SUM_DELITOS_MUNICIPIO_MES".ID_DELITO > "CAT_DELITOS_SECRETARIADO".ID_DELITO [color: #011B4E]
Ref: "SUM_DELITOS_MUNICIPIO_MES".ID_MES > "CAT_MESES".ID_MES [color: #011B4E]
Ref: "CAT_TIPO_DE_DELITO".ID_BIEN_JURIDICO_AFECTADO > "CAT_BIEN_JURIDICO_AFECTADO".ID_BIEN_JURIDICO_AFECTADO [color: #011B4E]
Ref: "CAT_SUBTIPO_DE_DELITO".ID_TIPO_DE_DELITO > "CAT_TIPO_DE_DELITO".ID_TIPO_DE_DELITO [color: #011B4E]
Ref: "CAT_DELITOS_SECRETARIADO".ID_MODALIDAD > "CAT_MODALIDAD".ID_MODALIDAD [color: #011B4E]
Ref: "CAT_DELITOS_SECRETARIADO".ID_SUBTIPO_DE_DELITO > "CAT_SUBTIPO_DE_DELITO".ID_SUBTIPO_DE_DELITO [color: #011B4E]

/**** FUENTES EXTERNAS ****/
Ref: "CAT_MODALIDAD_ANERPV"."ID_MODALIDAD_ANERPV" < "SUM_DELITOS_ENTIDAD_MES_MODALIDAD_ANERPV"."ID_MODALIDAD_ANERPV"
Ref: "SUM_DELITOS_MUNICIPIO_MES_ANERPV".CVE_MUNICIPIO > "CATALOGO_MUNICIPIO".CVE_MUNICIPIO [color: #1E69FD]
Ref: "SUM_DELITOS_MUNICIPIO_MES_ANERPV".ID_MES > "CAT_MESES".ID_MES [color: #1E69FD]
Ref: "SUM_DELITOS_ENTIDAD_MES_ANERPV".ID_ENTIDAD > "CAT_ENTIDAD".ID_ENTIDAD [color: #1E69FD]
Ref: "SUM_DELITOS_ENTIDAD_MES_ANERPV".ID_MES > "CAT_MESES".ID_MES [color: #1E69FD]
Ref: "SUM_DELITOS_NACIONAL_MES_ANERPV".ID_MES > "CAT_MESES".ID_MES [color: #1E69FD]
Ref: "SUM_DELITOS_ENTIDAD_MES_MODALIDAD_ANERPV".ID_ENTIDAD > "CAT_ENTIDAD".ID_ENTIDAD [color: #1E69FD]
Ref: "SUM_DELITOS_ENTIDAD_MES_MODALIDAD_ANERPV".ID_MES > "CAT_MESES".ID_MES [color: #1E69FD]

/**** REACCIONES ****/
Ref: "INCIDENTES_SKY".CVE_MUNICIPIO > "CATALOGO_MUNICIPIO".CVE_MUNICIPIO [color: #990D0D]
Ref: "INCIDENTES_SKY".ID_CATEGORIA > "CAT_CATEGORIAS".ID_CATEGORIA [color: #990D0D]
Ref: "CAT_CENTRAL".ID_CENTRAL < "INCIDENTES_SKY".ID_CENTRAL [color: #990D0D]
Ref: "CAT_LINEA_TRANSPORTISTA".ID_LINEA_TRANSPORTISTA < "INCIDENTES_SKY".ID_LINEA_TRANSPORTISTA [color: #990D0D]
Ref: "CAT_OPERADORES".ID_OPERADOR < "INCIDENTES_SKY".ID_OPERADOR [color: #990D0D]

/**** PUNTO DE INTERES ****/
Ref: "CAT_ENTIDAD"."ID_ENTIDAD" < "INT_ACCIDENTES"."ID_ENTIDAD" [color: #A15CF5]
Ref: "CAT_ENTIDAD"."ID_ENTIDAD" < "INT_RECUPERACION"."ID_ENTIDAD" [color: #A15CF5]
Ref: "CAT_ENTIDAD"."ID_ENTIDAD" < "INT_OTRAS_INCIDENCIAS"."ID_ENTIDAD" [color: #A15CF5]
Ref: "CAT_ENTIDAD"."ID_ENTIDAD" < "INT_INC_DELICTIVAS"."ID_ENTIDAD" [color: #A15CF5]
Ref: "CAT_ENTIDAD"."ID_ENTIDAD" < "INT_CACHIMBAS"."ID_ENTIDAD" [color: #A15CF5]
Ref: "CAT_ENTIDAD"."ID_ENTIDAD" < "INT_COBERTURA"."ID_ENTIDAD" [color: #A15CF5]
Ref: "CAT_ENTIDAD"."ID_ENTIDAD" < "INT_GUARDIA_NACIONAL"."ID_ENTIDAD" [color: #A15CF5]
Ref: "CAT_ENTIDAD"."ID_ENTIDAD" < "INT_CORRALONES"."ID_ENTIDAD" [color: #A15CF5]
Ref: "CAT_ENTIDAD"."ID_ENTIDAD" < "INT_MINISTERIOS_PUBLICOS"."ID_ENTIDAD" [color: #A15CF5]
Ref: "CAT_ENTIDAD"."ID_ENTIDAD" < "INT_PARADEROS"."ID_ENTIDAD" [color: #A15CF5]
Ref: "CATALOGO_MUNICIPIO"."CVE_MUNICIPIO" < "INT_ACCIDENTES"."CVE_MUNICIPIO" [color: #A15CF5]
Ref: "CATALOGO_MUNICIPIO"."CVE_MUNICIPIO" < "INT_RECUPERACION"."CVE_MUNICIPIO" [color: #A15CF5]
Ref: "CATALOGO_MUNICIPIO"."CVE_MUNICIPIO" < "INT_OTRAS_INCIDENCIAS"."CVE_MUNICIPIO" [color: #A15CF5]
Ref: "CATALOGO_MUNICIPIO"."CVE_MUNICIPIO" < "INT_INC_DELICTIVAS"."CVE_MUNICIPIO" [color: #A15CF5]
Ref: "CATALOGO_MUNICIPIO"."CVE_MUNICIPIO" < "INT_CACHIMBAS"."CVE_MUNICIPIO" [color: #A15CF5]
Ref: "CATALOGO_MUNICIPIO"."CVE_MUNICIPIO" < "INT_COBERTURA"."CVE_MUNICIPIO" [color: #A15CF5]
Ref: "CATALOGO_MUNICIPIO"."CVE_MUNICIPIO" < "INT_GUARDIA_NACIONAL"."CVE_MUNICIPIO" [color: #A15CF5]
Ref: "CATALOGO_MUNICIPIO"."CVE_MUNICIPIO" < "INT_CORRALONES"."CVE_MUNICIPIO" [color: #A15CF5]
Ref: "CATALOGO_MUNICIPIO"."CVE_MUNICIPIO" < "INT_MINISTERIOS_PUBLICOS"."CVE_MUNICIPIO" [color: #A15CF5]
Ref: "CATALOGO_MUNICIPIO"."CVE_MUNICIPIO" < "INT_PARADEROS"."CVE_MUNICIPIO" [color: #A15CF5]
Ref: "CAT_MESES"."ID_MES" < "INT_INC_DELICTIVAS"."MES" [color: #A15CF5]
Ref: "CAT_MESES"."ID_MES" < "INT_OTRAS_INCIDENCIAS"."MES" [color: #A15CF5]
Ref: "CAT_MESES"."ID_MES" < "INT_ACCIDENTES"."MES" [color: #A15CF5]
Ref: "CAT_MESES"."ID_MES" < "INT_RECUPERACION"."MES" [color: #A15CF5]

/**** ROBO Y VANDALISMO SISTEMA FERROVIARIO MEXICO ****/
Ref: "FER_SUBDELITOS"."ID_FER_SUBDELITO" < "FER_REGISTROS"."ID_FER_SUBDELITO" [color: #E4A62E]
Ref: "FER_DELITOS"."ID_FER_DELITO" < "FER_REGISTROS"."ID_FER_DELITO" [color: #E4A62E]
Ref: "FER_SUBDELITOS"."ID_FER_SUBDELITO" < "FER_DELITOS_SUBDELITOS"."ID_FER_SUBDELITO" [color: #E4A62E]
Ref: "FER_DELITOS"."ID_FER_DELITO" < "FER_DELITOS_SUBDELITOS"."ID_FER_DELITO" [color: #E4A62E]
Ref: "CATALOGO_MUNICIPIO"."CVE_MUNICIPIO" < "FER_REGISTROS"."CVE_MUNICIPIO" [color: #E4A62E]
Ref: "CAT_ENTIDAD"."ID_ENTIDAD" < "FER_REGISTROS"."ID_ENTIDAD" [color: #E4A62E]

/**** ALERTAS_SKY ****/
Ref: "ALERTAS_SKY"."ID_ESTATUS_ALERTA" < "CAT_ESTATUS_ALERTA"."ID_ESTATUS_ALERTA"